# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dd0d3acd7ee6b8e2dcf26e84ffb3a09f"
name = "small-custom-app"
handle = "small-custom-app"
application_url = "https://fountain-strip-phd-chevy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "webhooktestingstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_cart_transforms,read_all_checkout_completion_target_customizations,read_gdpr_data_request,read_analytics,read_assigned_fulfillment_orders,read_cart_transforms,read_cash_tracking,read_channels,read_companies,read_content,read_custom_fulfillment_services,read_custom_pixels,read_customer_data_erasure,read_customer_events,read_customer_merge,read_customers,read_delivery_customizations,read_delivery_option_generators,read_discounts,read_discounts_allocator_functions,read_discovery,read_draft_orders,read_files,read_fulfillment_constraint_rules,read_fulfillments,read_gates,read_gift_cards,read_inventory,read_legal_policies,read_locales,read_locations,read_marketing_events,read_markets,read_markets_home,read_merchant_managed_fulfillment_orders,read_metaobject_definitions,read_metaobjects,read_online_store_navigation,read_online_store_pages,read_order_edits,read_order_submission_rules,read_orders,read_packing_slip_templates,read_payment_customizations,read_payment_terms,read_pixels,read_price_rules,read_privacy_settings,read_product_feeds,read_product_listings,read_products,read_publications,read_purchase_options,read_reports,read_resource_feedbacks,read_returns,read_script_tags,read_shipping,read_shopify_payments_accounts,read_shopify_payments_bank_accounts,read_shopify_payments_disputes,read_shopify_payments_payouts,read_store_credit_account_transactions,read_store_credit_accounts,read_themes,read_third_party_fulfillment_orders,read_translations"

[auth]
redirect_urls = [
  "https://fountain-strip-phd-chevy.trycloudflare.com/auth/callback",
  "https://fountain-strip-phd-chevy.trycloudflare.com/auth/shopify/callback",
  "https://fountain-strip-phd-chevy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
